### ISSUE TITLE
items in creative item group are arranged out of order in forge-1.20.1-10

### ISSUE THREAD

**Issue by feroooooo** [Tfarcenim/Dank-Storage#250]
forge-1.20.1-8
![8](https://github.com/user-attachments/assets/9b0a781e-6432-479b-b25b-e36a505ef9d9)
forge-1.20.1-10
![10](https://github.com/user-attachments/assets/ba4abe70-4460-4d3f-90ed-cf9434f5d99f)

**Comment by Tfarcenim** [comment]
Fixed in 1.20.1-12

**Comment by feroooooo** [comment]
> Fixed in 1.20.1-12

I just update to 1.20.1-12 in ATM9TTS, and find this problem isn't fixed.

**Comment by Tfarcenim** [comment]
Order is locked when a world is created, it will show up when you create a new world.

**Comment by feroooooo** [comment]
> Order is locked when a world is created, it will show up when you create a new world.

get it， thanks
