### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by Darkere** [Tfarcenim/Dank-Storage#37]
Any chance we could get something a little smaller? :)
![image](https://user-images.githubusercontent.com/4283717/72759732-d329e600-3bd6-11ea-8249-6cb9e24c2f02.png)

**Comment by Tfarcenim** [comment]
mod version?

**Comment by Darkere** [comment]
dankstorage-2.4.jar
forge 30.0.41

https://github.com/Tfarcenim/Dank-Storage/blob/363786b80d2e19c2b5ddbf691d2093ce57c87026/src/main/java/tfar/dankstorage/DankBlock.java#L129

**Comment by Tfarcenim** [comment]
fixed

**Comment by Darkere** [comment]
Thank you!

**Comment by milkev** [comment]
this issue is still present in fabric, do we just have to wait for an update or?
