### ISSUE TITLE
[3.4][1.16.1] Filter option doesn't work

### ISSUE THREAD

**Issue by BarryBlackCat** [Tfarcenim/Dank-Storage#57]
When I changed to  FILTERED_PICKUP it supposed to grab only items that already in into dankstorage right? but it  doesn't work and this grab all types of items like in PICKUP_ALL mode.

Well, in 3.3a this is working 100%. Probably something related to this change u made in 3.4: https://github.com/Tfarcenim/Dank-Storage/issues/56#issuecomment-657685439

**Comment by Tfarcenim** [comment]
fixed in 3.6

**Comment by krazzykid2006** [comment]
It's still having issues and isn't fixed for me.
I just updated to 3.7 and now when I have the yellow or red pickup options selected it just deletes the items it picks up.
I am nowhere near max capacity for any slots, so even on the red selection it shouldn't be deleting things.

On the green pickup selection it's working and adding the items to the slots, but on anything else with pickup on it deletes them.
It does show it's little animation to show it picked items up but then I open it and it deleted them instead.

**Comment by Tfarcenim** [comment]
got reproduction steps?

**Comment by krazzykid2006** [comment]
1 Set to yellow pickup.
2 Take note of how many items a slot has
3 Took stack of cobble out
4 Opened player inventory
5 Threw cobble on ground (and then picked them up)
6 Opened Dank and noticed it was missing the 64 items

I then tried with a few more different items, tried setting it to red and repeated (same result), tried green and it worked normally. Went back to yellow and it did it 3 more times (every time).

**Comment by krazzykid2006** [comment]
Okay more testing. It's only doing it with some items and not others.
Dirt was added back correctly but end stone wasn't. Lily pads were deleted instead of being picked up. Etc.

**Comment by krazzykid2006** [comment]
The items it "deletes" are actually added to another slot as a different item.
For example, I have dirt in my first slot, and anything it "deletes" gets counted as dirt and added to my dirt slot.

Edit I think only the first slot is working for pickup when set to yellow or red. Everything else is deleted it seems.

**Comment by Tfarcenim** [comment]
lovely

**Comment by krazzykid2006** [comment]
3.7a seems to have resolved it for good.
Wasn't expecting it so fast. Thank you very much!
